### ISSUE TITLE
Power toggle only turns off

### ISSUE THREAD

**Issue by staxza** [brmccrary/nuvo_simple#2] opened 2024-02-18 16:36 UTC
It looks like the power status feedback is not updating on Nuvo Simplese
Therefore you can only use the power toggle to switch off but not on
When switching off the feedback shows the amps is on
Power on and power off works but toggle not

Anyways thanks very much for this integration. You just made my Nuvo Simplese usefull again.

**Comment by brmccrary** [comment] 2024-02-18 18:43
Thanks for letting me know, it really has not been tested on the Simplese that I know of.  I just looked at the protocol documents for both the Simplese and Essentia and can't figure out what would be different and causing it to fail.  Would you mind adding these lines to your configuration.yaml for me?

```
logger:
  logs:
    custom_components.nuvo_simple: debug
    nuvo_simple: debug

```
You may already have a logger section, but if you don't mind to add the logs: part.  Restart Home Assistant and try toggling the power again.  After you do so, please attach the log file.  You can filter out only the stuff needed from the logs by going to Settings, Logs, then select  load full log, and the searching at the top bar for nuvo_simple.  You could then just copy and paste that.  Of course, you could use grep too, just whatever is easiest for you.  Thanks for your help!

**Comment by sooperdoopa** [comment] 2024-06-01 22:29
I have this same issue since updating HA.  I can power on and off via script but the integration with mini-media player has this problem since a recent update of HA.

**Comment by brmccrary** [comment] 2024-06-02 17:18
Can not reproduce the main issue reported.  No additional information was provided.  Closing issue.

**Closed as completed** 2024-06-02 17:18 UTC

**Comment by jacob-moses** [comment] 2025-08-01 20:46
@brmccrary Thanks so much for this integration! I’m having the same issue as reported by @staxza.

I also have a Nuvo Simplese. Here’s the behavior I’m observing in my Home Assistant integration.

1. Nuvo amplifier zone off | HA media player displays zone off
2. Press power button on HA media player zone
3. Nuvo amplifier zone on | HA media player displays zone on
4. Press power button on HA media player zone
5. Nuvo amplifier zone **off** | HA media player displays **on**
6. If I open the media player, and click “Apply” that seems to force HA to request an update from the Nuvo, which updates the HA media player display to **off** (and allowing the amplifier to be turned back on).

<img width="804" height="568" alt="Image" src="https://github.com/user-attachments/assets/a54df720-572a-46e9-bd00-3afd5cd487e9" />

Here are the relevant logs:
—
2025-08-01 15:37:01.402 DEBUG (Thread-3 (_send_request)) [nuvo_simple] Sending "Z03ON"
2025-08-01 15:37:01.475 DEBUG (Thread-4 (_listen)) [nuvo_simple] Received: b'#Z03PWRON,SRC2,GRP0,VOL-24'
2025-08-01 15:37:01.475 DEBUG (Thread-4 (_listen)) [nuvo_simple] CONSR received
2025-08-01 15:37:01.475 DEBUG (Thread-4 (_listen)) [custom_components.nuvo_simple.media_player] Zone 3 media player update called
2025-08-01 15:37:01.476 DEBUG (Thread-4 (_listen)) [nuvo_simple] Zone: 3, Power: True, Vol: -24db, 50%, Mute: False, Source: 2, Init: 1
2025-08-01 15:37:01.477 DEBUG (SyncWorker_0) [nuvo_simple] Zone: 3, Power: True, Vol: -24db, 50%, Mute: False, Source: 2, Init: 1
2025-08-01 15:37:08.424 DEBUG (Thread-3 (_send_request)) [nuvo_simple] Sending "Z03OFF"
2025-08-01 15:37:08.451 DEBUG (Thread-4 (_listen)) [nuvo_simple] Received: b'#Z03PWROFF'
2025-08-01 15:37:16.110 DEBUG (SyncWorker_6) [custom_components.nuvo_simple.media_player] Zone 3 adding [] to group
2025-08-01 15:37:16.110 DEBUG (SyncWorker_6) [custom_components.nuvo_simple.media_player] Zone 3 media player update called
2025-08-01 15:37:16.112 DEBUG (SyncWorker_5) [nuvo_simple] Zone: 3, Power: False, Vol: -24db, 50%, Mute: False, Source: 2, Init: 1
2025-08-01 15:37:20.852 DEBUG (Thread-3 (_send_request)) [nuvo_simple] Sending "Z03ON"
2025-08-01 15:37:20.915 DEBUG (Thread-4 (_listen)) [nuvo_simple] Received: b'#Z03PWRON,SRC2,GRP0,VOL-24'
2025-08-01 15:37:20.916 DEBUG (Thread-4 (_listen)) [nuvo_simple] CONSR received
2025-08-01 15:37:20.916 DEBUG (Thread-4 (_listen)) [custom_components.nuvo_simple.media_player] Zone 3 media player update called
2025-08-01 15:37:20.916 DEBUG (Thread-4 (_listen)) [nuvo_simple] Zone: 3, Power: True, Vol: -24db, 50%, Mute: False, Source: 2, Init: 1
2025-08-01 15:37:20.917 DEBUG (SyncWorker_0) [nuvo_simple] Zone: 3, Power: True, Vol: -24db, 50%, Mute: False, Source: 2, Init: 1
—

Any help would be greatly appreciated!

**Comment by brmccrary** [comment] 2025-08-01 22:44
Hi @jacob-moses ,

I'm opening a new issue for this as it is a different problem than the one addressed here.  See #5 .  The problem looks like the Simplese sends a different power off message than the Essentia or the Concerto so it's not recognized.  Should be able to fix this weekend.
